In [1]:
import numpy as np
import pickle

In [3]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
model = pickle.load(open('models/model.pkl', 'rb'))

In [15]:
test_input = np.array([2, 'male', 22.0, 0, 2, 10.2458, 'S'], dtype='object').reshape(1, 7)

In [19]:
test_input

array([[2, 'male', 22.0, 0, 2, 10.2458, 'S']], dtype=object)

In [37]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

C:\Users\12368\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
C:\Users\12368\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [39]:
test_input_embarked

array([[0, 1, 0]])

In [41]:
test_input_age = test_input[:, 2].reshape(1,1)

In [43]:
test_input_age

array([[22.0]], dtype=object)

In [47]:
test_input_transformed = np.concatenate((test_input[:, [0, 3, 4, 5]], test_input_sex, test_input_age, test_input_embarked), axis=1)

In [51]:
test_input_transformed

array([[2, 0, 2, 10.2458, 1, 22.0, 0, 1, 0]], dtype=object)